name: Build Python distribution packages

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Artifact name"
        required: false
        type: string
        default: "python-package-dist"
      artifact-path:
        description: "A file, directory or a wildcard that describes the artifact to upload"
        required: false
        type: string
        default: "dist/"
      build-command:
        description: "Command(s) to build the package"
        required: false
        type: string
        default: "python3 -m build"
      dependencies-command:
        description: "Command(s) used for installing the build dependencies"
        required: false
        type: string
        default: "python3 -m pip install --user build"
      python-version:
        description: "Python version to use for build"
        required: false
        type: string
        default: "3.x"
      ref:
        description: "The branch, tag or SHA to publish."
        required: false
        type: string
    outputs:
      artifact_name:
        description: "Name of the uploaded artifact. Empty if no artifact was created."
        value: ${{ jobs.build.outputs.artifact_name }}

jobs:
  build:
    name: Build distribution packages
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.set-artifact-name.outputs.artifact_name }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false  # don"t persist git credentials on disk
          ref: ${{ inputs.ref == null && null || inputs.ref }}
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install build dependencies
        run: ${{ inputs.dependencies-command }}
      - name: Build the distributions
        run: ${{ inputs.build-command }}
      - name: Store the distributions
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
      - name: Set artifact name on success
        id: set-artifact-name
        if: ${{ success() }}
        run: echo "artifact_name=${{ inputs.artifact-name }}" >> $GITHUB_OUTPUT
