name: npm publish

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
      use-ci-build:
        description: 'Use build artifacts from CI workflow (requires ci-node workflow to run first)'
        required: false
        default: false
        type: boolean
      install-command:
        description: 'Command to install dependencies'
        required: false
        type: string
        default: 'yarn --frozen-lockfile'
      test-command:
        description: 'Command to run tests'
        required: false
        type: string
        default: 'yarn test'
      build-command:
        description: 'Command to build the package'
        required: false
        type: string
        default: 'yarn build'
      registry-url:
        description: 'npm registry URL'
        required: false
        type: string
        default: 'https://registry.npmjs.org/'
      access:
        description: 'Package access level (public, restricted)'
        required: false
        type: string
        default: 'public'
      canary:
        description: 'Make publish as a canary release'
        required: false
        type: boolean
        default: false

jobs:
  publish-npm-stable:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}
      - name: Upgrade npm to latest
        run: npm install -g npm@latest
      - name: Download build artifacts
        if: ${{ inputs.use-ci-build }}
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: build-artifacts-${{ inputs.node-version }}
          path: ./
      - name: Install dependencies
        if: ${{ !inputs.use-ci-build }}
        run: ${{ inputs.install-command }}
      - name: Run tests
        if: ${{ !inputs.use-ci-build }}
        run: ${{ inputs.test-command }}
      - name: Build package
        if: ${{ !inputs.use-ci-build }}
        run: ${{ inputs.build-command }}
      - name: Publish package
        if: ${{ !inputs.canary }}
        run: npm publish --ignore-scripts --access ${{ inputs.access }}
        env:
          NPM_CONFIG_PROVENANCE: true
      - name: Publish canary package
        if: ${{ inputs.canary }}
        run: |
          short_sha=$(git rev-parse --short HEAD)
          sed -i -E "s/\"version\": \"([^\"]+)\"/\"version\": \"\1-canary-${short_sha}\"/" package.json
          npm publish --ignore-scripts --access ${{ inputs.access }} --tag canary
        env:
          NPM_CONFIG_PROVENANCE: true
