name: npm publish

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
      use-ci-build:
        description: 'Use build artifacts from CI workflow (requires ci-node workflow to run first)'
        required: false
        default: false
        type: boolean
      install-command:
        description: 'Command to install dependencies'
        required: false
        type: string
        default: 'yarn --frozen-lockfile'
      test-command:
        description: 'Command to run tests'
        required: false
        type: string
        default: 'yarn test'
      build-command:
        description: 'Command to build the package'
        required: false
        type: string
        default: 'yarn build'
      registry-url:
        description: 'npm registry URL'
        required: false
        type: string
        default: 'https://registry.npmjs.org/'
      access:
        description: 'Package access level (public, restricted)'
        required: false
        type: string
        default: 'public'
      canary:
        description: 'Make publish as a canary release'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  publish-npm-stable:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}
      - name: Upgrade npm to latest
        run: npm install -g npm@latest
      - name: Download build artifacts
        if: ${{ inputs.use-ci-build }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-artifacts-${{ inputs.node-version }}
          path: ./
      - name: Install dependencies
        if: ${{ !inputs.use-ci-build }}
        run: ${{ inputs.install-command }}
      - name: Run tests
        if: ${{ !inputs.use-ci-build }}
        run: ${{ inputs.test-command }}
      - name: Build package
        if: ${{ !inputs.use-ci-build }}
        run: ${{ inputs.build-command }}
      - name: Publish package
        if: ${{ !inputs.canary }}
        run: npm publish --ignore-scripts --access ${{ inputs.access }}
        env:
          NPM_CONFIG_PROVENANCE: true
      - name: Publish canary package
        if: ${{ inputs.canary }}
        run: |
          short_sha=$(git rev-parse --short HEAD)
          sed -i -E "s/\"version\": \"([^\"]+)\"/\"version\": \"\1-canary-${short_sha}\"/" package.json
          npm publish --ignore-scripts --access ${{ inputs.access }} --tag canary
        env:
          NPM_CONFIG_PROVENANCE: true
