name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ vars.ORGANIZATIONTOKEN_APP_ID }}
          private-key: ${{ secrets.ORGANIZATIONTOKEN_PRIVATE_KEY }}
          # Set the owner, so the token can be used in all repositories
          owner: ${{ github.repository_owner }}
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@8b92be3375cf1d1b0cd579af488a9255572e4619 # v1.21.1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.app-token.outputs.token}}
          GIT_EMAIL: sync.bot@example.com
          GIT_USERNAME: github-sync[bot]
          COMMIT_PREFIX: "chore: file sync update\n\nSigned-off-by: sol-office-file-synchronization[bot]\n\nSync:"
